# 层次分析法 AHP

## 模型

根据指标两两之间的权重比值，推算各指标的权重

e.g.

![image.png](https://s2.loli.net/2025/08/10/iVM9bx4On5A8jvH.png)

## 实现

In [13]:
import numpy as np

#! 修改评价矩阵
criteria = np.array(
    [[1, 1 / 3, 1 / 8],
     [3, 1, 1 / 3],
     [8, 3, 1]]
)

In [14]:
n = criteria.shape[0]
# 初始化RI值，用于一致性检验
RI_list = [0, 0, 0.52, 0.89, 1.12, 1.26, 1.36, 1.41, 1.46, 1.49, 1.52, 1.54, 1.56, 1.58,
                1.59]
# 矩阵的特征值和特征向量
eig_val, eig_vector = np.linalg.eig(criteria)
# 矩阵的最大特征值
max_eig_val = np.max(eig_val)
# 矩阵最大特征值对应的特征向量
max_eig_vector = eig_vector[:, np.argmax(eig_val)].real # type: ignore
# 矩阵的一致性指标CI
CI_val = (max_eig_val - n) / (n - 1)
# 矩阵的一致性比例CR
CR_val = CI_val / (RI_list[n - 1])

In [15]:
 # 打印矩阵的一致性指标CI和一致性比例CR
print("判断矩阵的CI值为：" + str(CI_val))
print("判断矩阵的CR值为：" + str(CR_val))
# 进行一致性检验判断
if n == 2:  # 当只有两个子因素的情况
    print("仅包含两个子因素，不存在一致性问题")
else:
    if CR_val < 0.1:  # CR值小于0.1，可以通过一致性检验
        print("判断矩阵的CR值为" + str(CR_val) + ",通过一致性检验")
    else:  # CR值大于0.1, 一致性检验不通过
        print("判断矩阵的CR值为" + str(CR_val) + "未通过一致性检验")

判断矩阵的CI值为：(0.0007708125321126413+0j)
判断矩阵的CR值为：(0.0014823317925243102+0j)
判断矩阵的CR值为(0.0014823317925243102+0j),通过一致性检验


In [16]:
# 求矩阵的每列的和
col_sum = np.sum(criteria, axis=0)
# 将判断矩阵按照列归一化
array_normed = criteria / col_sum
# 计算权重向量
array_weight = np.sum(array_normed, axis=1) / n
# 打印权重向量
print("算术平均法计算得到的权重向量为：\n", array_weight)

算术平均法计算得到的权重向量为：
 [0.08199023 0.23644689 0.68156288]


In [17]:
col_product = np.prod(criteria, axis=0)
# 将得到的积向量的每个分量进行开n次方
array_power = np.power(col_product, 1 / criteria.shape[0])
# 将列向量归一化
array_weight = array_power / np.sum(array_power)
# 打印权重向量
print("几何平均法计算得到的权重向量为：\n", array_weight)

几何平均法计算得到的权重向量为：
 [0.68172455 0.2363407  0.08193475]


In [18]:
# 将矩阵最大特征值对应的特征向量进行归一化处理就得到了权重
array_weight = max_eig_vector / np.sum(max_eig_vector)
# 打印权重向量
print("特征值法计算得到的权重向量为：\n", array_weight)

特征值法计算得到的权重向量为：
 [0.08193475 0.2363407  0.68172455]
