# 灰色关联分析

## 模型

通过比较两个指标的变化曲线趋势，判断两个指标的相关性

## 实现

In [13]:
import numpy as np

#! 修改输入数据
data = np.array([
    [55, 24, 10],
    [65, 38, 22],
    [75, 40, 18],
    [100, 50, 20],
])

#! 修改分辨系数
RHO = 0.5

In [14]:
# 预处理
mean = np.mean(data, axis=0)

data_norm = data / mean

print("预处理后数据：", data_norm)

预处理后数据： [[0.74576271 0.63157895 0.57142857]
 [0.88135593 1.         1.25714286]
 [1.01694915 1.05263158 1.02857143]
 [1.3559322  1.31578947 1.14285714]]


In [15]:
# 母序列
Y = data_norm[:, 0]
# 子序列
X = data_norm[:, 1:]

# |X_0-X_i|，其中 Y = X_0
absx0xi = np.abs(X - np.tile(Y.reshape(-1, 1), (1, X.shape[1])))
# 最小差
a = np.min(absx0xi)
# 最大差
b = np.max(absx0xi)

# 计算子序列关联系数
gamma = (a + RHO * b) / (absx0xi + RHO * b)
print("子序列中各指标灰色关联度：", np.mean(gamma, axis=0))

子序列中各指标灰色关联度： [0.76966578 0.60058464]
