# 数据转换

## 归一化

把数据缩到 $[0, 1]$ 或 $[-1, 1]$ 之间

- 数据上下界已知

In [22]:
import numpy as np

#! 修改输入数据
# 行为对象，列为指标
data = np.array([
    [1,  -3.2],
    [88,  6.9],
    [79,  29.1],
    [22,  13.9],
])

data

array([[ 1. , -3.2],
       [88. ,  6.9],
       [79. , 29.1],
       [22. , 13.9]])

In [23]:
from sklearn.preprocessing import minmax_scale, MinMaxScaler

data = minmax_scale(data, 
    # 归一区间
    feature_range=(0,1),
)

data

array([[0.        , 0.        ],
       [1.        , 0.3126935 ],
       [0.89655172, 1.        ],
       [0.24137931, 0.52941176]])

## 标准化

将数据转换成均值为0，标准差为1的标准正态分布

- 数据必须本身遵循正态分布

- 对异常值不敏感

In [24]:
import numpy as np

#! 修改输入数据
# 行为对象，列为指标
data = np.array([
    [1,  -3.2],
    [88,  6.9],
    [79,  29.1],
    [22,  13.9],
])

data

array([[ 1. , -3.2],
       [88. ,  6.9],
       [79. , 29.1],
       [22. , 13.9]])

In [25]:
from sklearn.preprocessing import StandardScaler

data = StandardScaler().fit_transform(data)

data

array([[-1.26032922, -1.26550209],
       [ 1.0977061 , -0.4062368 ],
       [ 0.85377141,  1.4824453 ],
       [-0.69114828,  0.18929359]])